backend:
  name: git-gateway
  branch: main

media_folder: "public/images/gallery"
public_folder: "/images/gallery"

collections:
  - name: "gallery"
    label: "Gallery"
    files:
      - label: "Gallery Images"
        name: "images"
        file: "src/data/gallery.json"
        fields:
          - label: "Images"
            name: "images"
            widget: "list"
            fields:
              - { label: "Image", name: "url", widget: "image" }
              - { label: "Alt Text", name: "alt", widget: "string" }
              - {
                  label: "Caption",
                  name: "caption",
                  widget: "string",
                  required: false,
                }
