backend:
  name: git-gateway
  branch: main

media_folder: "public/images/gallery"
public_folder: "/images/gallery"

collections:
  - name: "gallery"
    label: "Gallery Images"
    folder: "src/data/gallery"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Caption", name: "caption", widget: "string", required: false }
      - { label: "Alt Text", name: "alt", widget: "string" }
